name: btleplug
description: Dart plugin for btleplug.
version: 0.1.0
repository: https://github.com/trobanga/flutter_btleplug
issue_tracker: https://github.com/trobanga/flutter_btleplug/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  ffigen: ">=8.0.2 <11.0.0"
  freezed: ^2.4.5
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.63.1
  freezed_annotation: ^2.4.1
  meta: ^1.8.0
  uuid: ^3.0.7
