name: btleplug
description: Dart plugin for btleplug.
version: 0.1.0
repository: https://github.com/trobanga/flutter_btleplug
issue_tracker: https://github.com/trobanga/flutter_btleplug/issues

environment:
  sdk: '>=2.19.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  ffigen: ^7.2.6
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.63.1
  meta: ^1.8.0
  uuid: ^3.0.7
