[package]
name = "btleplug"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.72.2"

[dependencies]
anyhow = "1.0.70"
btleplug = "0.10.4"
crossbeam-channel = "0.5.8"
flutter_rust_bridge = "1.72.2"
futures = "0.3.28"
jni = "0.19.0"
jni-utils = "0.1.0"
once_cell = "1.17.1"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["rt", "sync", "rt-multi-thread", "time"] }
tokio-stream = { version = "0.1.12", features = ["sync"] }
